# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib/qt/cnctoolbox/mainwindow.ui'
#
# Created: Wed Apr 15 19:26:29 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 674)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("#lcdNumber_mx { color: #ab1111; }\n"
"#lcdNumber_my { color: #ab1111; }\n"
"#lcdNumber_mz { color: #ab1111; }\n"
"#lcdNumber_wx { color: #0e8005; }\n"
"#lcdNumber_wy { color: #0e8005; }\n"
"#lcdNumber_wz { color: #0e8005; }\n"
"#lcdNumber_mx { color: #ab1111; }\n"
"#lcdNumber_my { color: #ab1111; }\n"
"#lcdNumber_mz { color: #ab1111; }")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_w2mcoord = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(False)
        self.pushButton_w2mcoord.setFont(font)
        self.pushButton_w2mcoord.setObjectName("pushButton_w2mcoord")
        self.gridLayout.addWidget(self.pushButton_w2mcoord, 7, 1, 1, 1)
        self.pushButton_xplus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_xplus.setObjectName("pushButton_xplus")
        self.gridLayout.addWidget(self.pushButton_xplus, 11, 1, 1, 1)
        self.pushButton_xminus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_xminus.setObjectName("pushButton_xminus")
        self.gridLayout.addWidget(self.pushButton_xminus, 11, 0, 1, 1)
        self.pushButton_killalarm = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_killalarm.setObjectName("pushButton_killalarm")
        self.gridLayout.addWidget(self.pushButton_killalarm, 16, 9, 1, 1)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.gridLayout.addWidget(self.pushButton_disconnect, 0, 1, 1, 1)
        self.pushButton_connect = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout.addWidget(self.pushButton_connect, 0, 0, 1, 1)
        self.pushButton_hold = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_hold.setObjectName("pushButton_hold")
        self.gridLayout.addWidget(self.pushButton_hold, 16, 6, 1, 1)
        self.pushButton_g0wzero = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_g0wzero.setObjectName("pushButton_g0wzero")
        self.gridLayout.addWidget(self.pushButton_g0wzero, 9, 0, 1, 1)
        self.pushButton_zeroxy = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_zeroxy.setObjectName("pushButton_zeroxy")
        self.gridLayout.addWidget(self.pushButton_zeroxy, 8, 0, 1, 1)
        self.pushButton_g0wzerosafe = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_g0wzerosafe.setObjectName("pushButton_g0wzerosafe")
        self.gridLayout.addWidget(self.pushButton_g0wzerosafe, 9, 1, 1, 1)
        self.verticalLayout_cmd = QtWidgets.QVBoxLayout()
        self.verticalLayout_cmd.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_cmd.setObjectName("verticalLayout_cmd")
        self.gridLayout.addLayout(self.verticalLayout_cmd, 13, 12, 1, 3)
        self.pushButton_zeroz = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_zeroz.setObjectName("pushButton_zeroz")
        self.gridLayout.addWidget(self.pushButton_zeroz, 8, 1, 1, 1)
        self.pushButton_zplus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_zplus.setObjectName("pushButton_zplus")
        self.gridLayout.addWidget(self.pushButton_zplus, 13, 1, 1, 1)
        self.verticalLayout_xyz = QtWidgets.QVBoxLayout()
        self.verticalLayout_xyz.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_xyz.setObjectName("verticalLayout_xyz")
        self.lcdNumber_mx = QtWidgets.QLCDNumber(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_mx.sizePolicy().hasHeightForWidth())
        self.lcdNumber_mx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_mx.setFont(font)
        self.lcdNumber_mx.setDigitCount(8)
        self.lcdNumber_mx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_mx.setProperty("value", 8888.888)
        self.lcdNumber_mx.setObjectName("lcdNumber_mx")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_mx)
        self.lcdNumber_my = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_my.setFont(font)
        self.lcdNumber_my.setDigitCount(8)
        self.lcdNumber_my.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_my.setProperty("value", 8888.888)
        self.lcdNumber_my.setObjectName("lcdNumber_my")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_my)
        self.lcdNumber_mz = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_mz.setFont(font)
        self.lcdNumber_mz.setSmallDecimalPoint(False)
        self.lcdNumber_mz.setDigitCount(8)
        self.lcdNumber_mz.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_mz.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_mz.setProperty("value", 8888.888)
        self.lcdNumber_mz.setObjectName("lcdNumber_mz")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_mz)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_xyz.addItem(spacerItem)
        self.lcdNumber_wx = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_wx.setFont(font)
        self.lcdNumber_wx.setDigitCount(8)
        self.lcdNumber_wx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_wx.setProperty("value", 8888.888)
        self.lcdNumber_wx.setObjectName("lcdNumber_wx")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_wx)
        self.lcdNumber_wy = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_wy.setFont(font)
        self.lcdNumber_wy.setDigitCount(8)
        self.lcdNumber_wy.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_wy.setProperty("value", 8888.888)
        self.lcdNumber_wy.setObjectName("lcdNumber_wy")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_wy)
        self.lcdNumber_wz = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_wz.setFont(font)
        self.lcdNumber_wz.setDigitCount(8)
        self.lcdNumber_wz.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_wz.setProperty("value", 8888.888)
        self.lcdNumber_wz.setObjectName("lcdNumber_wz")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_wz)
        self.gridLayout.addLayout(self.verticalLayout_xyz, 4, 0, 2, 2)
        self.pushButton_homing = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_homing.setObjectName("pushButton_homing")
        self.gridLayout.addWidget(self.pushButton_homing, 16, 10, 1, 1)
        self.pushButton_resume = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_resume.setObjectName("pushButton_resume")
        self.gridLayout.addWidget(self.pushButton_resume, 16, 7, 1, 1)
        self.label_distancemode = QtWidgets.QLabel(self.centralWidget)
        self.label_distancemode.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_distancemode.setObjectName("label_distancemode")
        self.gridLayout.addWidget(self.label_distancemode, 6, 0, 1, 1)
        self.pushButton_yplus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_yplus.setObjectName("pushButton_yplus")
        self.gridLayout.addWidget(self.pushButton_yplus, 12, 0, 1, 1)
        self.checkBox_feedoverride = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_feedoverride.setObjectName("checkBox_feedoverride")
        self.gridLayout.addWidget(self.checkBox_feedoverride, 16, 0, 1, 1)
        self.pushButton_abort = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_abort.setFont(font)
        self.pushButton_abort.setAutoFillBackground(False)
        self.pushButton_abort.setStyleSheet("")
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.gridLayout.addWidget(self.pushButton_abort, 16, 8, 1, 1)
        self.label_arcdistancemode = QtWidgets.QLabel(self.centralWidget)
        self.label_arcdistancemode.setObjectName("label_arcdistancemode")
        self.gridLayout.addWidget(self.label_arcdistancemode, 6, 1, 1, 1)
        self.pushButton_zeroxyz = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_zeroxyz.setObjectName("pushButton_zeroxyz")
        self.gridLayout.addWidget(self.pushButton_zeroxyz, 7, 0, 1, 1)
        self.label_state = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state.sizePolicy().hasHeightForWidth())
        self.label_state.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_state.setFont(font)
        self.label_state.setStyleSheet("")
        self.label_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state.setObjectName("label_state")
        self.gridLayout.addWidget(self.label_state, 0, 5, 1, 1)
        self.pushButton_zminus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_zminus.setObjectName("pushButton_zminus")
        self.gridLayout.addWidget(self.pushButton_zminus, 13, 0, 1, 1)
        self.horizontalSlider_feed = QtWidgets.QSlider(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_feed.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_feed.setSizePolicy(sizePolicy)
        self.horizontalSlider_feed.setMinimum(100)
        self.horizontalSlider_feed.setMaximum(2000)
        self.horizontalSlider_feed.setSingleStep(50)
        self.horizontalSlider_feed.setPageStep(100)
        self.horizontalSlider_feed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_feed.setInvertedAppearance(False)
        self.horizontalSlider_feed.setInvertedControls(False)
        self.horizontalSlider_feed.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_feed.setTickInterval(100)
        self.horizontalSlider_feed.setObjectName("horizontalSlider_feed")
        self.gridLayout.addWidget(self.horizontalSlider_feed, 16, 5, 1, 1)
        self.pushButton_yminus = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_yminus.sizePolicy().hasHeightForWidth())
        self.pushButton_yminus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_yminus.setFont(font)
        self.pushButton_yminus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_yminus.setDefault(False)
        self.pushButton_yminus.setFlat(False)
        self.pushButton_yminus.setObjectName("pushButton_yminus")
        self.gridLayout.addWidget(self.pushButton_yminus, 12, 1, 1, 1)
        self.lcdNumber_feed = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber_feed.setDigitCount(5)
        self.lcdNumber_feed.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_feed.setProperty("value", 100.0)
        self.lcdNumber_feed.setProperty("intValue", 100)
        self.lcdNumber_feed.setObjectName("lcdNumber_feed")
        self.gridLayout.addWidget(self.lcdNumber_feed, 16, 1, 1, 1)
        self.grid_opengl = QtWidgets.QGridLayout()
        self.grid_opengl.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.grid_opengl.setObjectName("grid_opengl")
        self.centerTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.centerTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.centerTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centerTabWidget.setObjectName("centerTabWidget")
        self.glTab = QtWidgets.QWidget()
        self.glTab.setObjectName("glTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.glTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.glTabGrid = QtWidgets.QGridLayout()
        self.glTabGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.glTabGrid.setHorizontalSpacing(4)
        self.glTabGrid.setObjectName("glTabGrid")
        self.gridLayout_2.addLayout(self.glTabGrid, 0, 0, 1, 1)
        self.centerTabWidget.addTab(self.glTab, "")
        self.conversationTab = QtWidgets.QWidget()
        self.conversationTab.setObjectName("conversationTab")
        self.pocketButton = QtWidgets.QPushButton(self.conversationTab)
        self.pocketButton.setGeometry(QtCore.QRect(20, 140, 121, 41))
        self.pocketButton.setObjectName("pocketButton")
        self.pocketButtonLabel = QtWidgets.QLabel(self.conversationTab)
        self.pocketButtonLabel.setGeometry(QtCore.QRect(20, 180, 121, 21))
        self.pocketButtonLabel.setObjectName("pocketButtonLabel")
        self.settingsGroupBox = QtWidgets.QGroupBox(self.conversationTab)
        self.settingsGroupBox.setGeometry(QtCore.QRect(459, 20, 161, 191))
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.bitDiameterLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.bitDiameterLabel.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.bitDiameterLabel.setObjectName("bitDiameterLabel")
        self.bitDiameterLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.bitDiameterLineEdit.setGeometry(QtCore.QRect(10, 60, 81, 33))
        self.bitDiameterLineEdit.setObjectName("bitDiameterLineEdit")
        self.argumentsGroupBox = QtWidgets.QGroupBox(self.conversationTab)
        self.argumentsGroupBox.setGeometry(QtCore.QRect(10, 20, 431, 121))
        self.argumentsGroupBox.setObjectName("argumentsGroupBox")
        self.dLineEdit = QtWidgets.QLineEdit(self.argumentsGroupBox)
        self.dLineEdit.setGeometry(QtCore.QRect(360, 60, 51, 33))
        self.dLineEdit.setObjectName("dLineEdit")
        self.syLineEdit = QtWidgets.QLineEdit(self.argumentsGroupBox)
        self.syLineEdit.setGeometry(QtCore.QRect(80, 60, 51, 33))
        self.syLineEdit.setObjectName("syLineEdit")
        self.rLabel = QtWidgets.QLabel(self.argumentsGroupBox)
        self.rLabel.setGeometry(QtCore.QRect(290, 30, 66, 21))
        self.rLabel.setObjectName("rLabel")
        self.syLabel = QtWidgets.QLabel(self.argumentsGroupBox)
        self.syLabel.setGeometry(QtCore.QRect(80, 30, 66, 21))
        self.syLabel.setObjectName("syLabel")
        self.eyLabel = QtWidgets.QLabel(self.argumentsGroupBox)
        self.eyLabel.setGeometry(QtCore.QRect(220, 30, 66, 21))
        self.eyLabel.setObjectName("eyLabel")
        self.eyLineEdit = QtWidgets.QLineEdit(self.argumentsGroupBox)
        self.eyLineEdit.setGeometry(QtCore.QRect(220, 60, 51, 33))
        self.eyLineEdit.setObjectName("eyLineEdit")
        self.exLineEdit = QtWidgets.QLineEdit(self.argumentsGroupBox)
        self.exLineEdit.setGeometry(QtCore.QRect(150, 60, 51, 33))
        self.exLineEdit.setObjectName("exLineEdit")
        self.dLabel = QtWidgets.QLabel(self.argumentsGroupBox)
        self.dLabel.setGeometry(QtCore.QRect(360, 30, 66, 21))
        self.dLabel.setObjectName("dLabel")
        self.exLabel = QtWidgets.QLabel(self.argumentsGroupBox)
        self.exLabel.setGeometry(QtCore.QRect(150, 30, 66, 21))
        self.exLabel.setObjectName("exLabel")
        self.sxLabel = QtWidgets.QLabel(self.argumentsGroupBox)
        self.sxLabel.setGeometry(QtCore.QRect(10, 30, 66, 21))
        self.sxLabel.setObjectName("sxLabel")
        self.sxLineEdit = QtWidgets.QLineEdit(self.argumentsGroupBox)
        self.sxLineEdit.setGeometry(QtCore.QRect(10, 60, 51, 33))
        self.sxLineEdit.setObjectName("sxLineEdit")
        self.rLineEdit = QtWidgets.QLineEdit(self.argumentsGroupBox)
        self.rLineEdit.setGeometry(QtCore.QRect(290, 60, 51, 33))
        self.rLineEdit.setObjectName("rLineEdit")
        self.centerTabWidget.addTab(self.conversationTab, "")
        self.scriptTab = QtWidgets.QWidget()
        self.scriptTab.setObjectName("scriptTab")
        self.scriptTextEdit = QtWidgets.QPlainTextEdit(self.scriptTab)
        self.scriptTextEdit.setGeometry(QtCore.QRect(10, 10, 661, 391))
        font = QtGui.QFont()
        font.setFamily("Linux Libertine Mono O")
        font.setPointSize(11)
        self.scriptTextEdit.setFont(font)
        self.scriptTextEdit.setObjectName("scriptTextEdit")
        self.linesToExecuteLabel = QtWidgets.QLabel(self.scriptTab)
        self.linesToExecuteLabel.setGeometry(QtCore.QRect(320, 410, 66, 21))
        self.linesToExecuteLabel.setObjectName("linesToExecuteLabel")
        self.filenameLineEdit = QtWidgets.QLineEdit(self.scriptTab)
        self.filenameLineEdit.setEnabled(True)
        self.filenameLineEdit.setGeometry(QtCore.QRect(12, 430, 301, 33))
        self.filenameLineEdit.setText("")
        self.filenameLineEdit.setObjectName("filenameLineEdit")
        self.filenameLabel = QtWidgets.QLabel(self.scriptTab)
        self.filenameLabel.setGeometry(QtCore.QRect(10, 410, 66, 21))
        self.filenameLabel.setObjectName("filenameLabel")
        self.loadScriptButton = QtWidgets.QPushButton(self.scriptTab)
        self.loadScriptButton.setGeometry(QtCore.QRect(470, 430, 61, 31))
        self.loadScriptButton.setObjectName("loadScriptButton")
        self.windowScopeCheckbox = QtWidgets.QCheckBox(self.scriptTab)
        self.windowScopeCheckbox.setGeometry(QtCore.QRect(130, 470, 95, 26))
        self.windowScopeCheckbox.setObjectName("windowScopeCheckbox")
        self.compilerScopeCheckbox = QtWidgets.QCheckBox(self.scriptTab)
        self.compilerScopeCheckbox.setGeometry(QtCore.QRect(20, 470, 95, 26))
        self.compilerScopeCheckbox.setChecked(True)
        self.compilerScopeCheckbox.setObjectName("compilerScopeCheckbox")
        self.executeScriptButton = QtWidgets.QPushButton(self.scriptTab)
        self.executeScriptButton.setGeometry(QtCore.QRect(540, 430, 71, 31))
        self.executeScriptButton.setObjectName("executeScriptButton")
        self.linesToExecute = QtWidgets.QLineEdit(self.scriptTab)
        self.linesToExecute.setGeometry(QtCore.QRect(320, 430, 71, 33))
        self.linesToExecute.setObjectName("linesToExecute")
        self.saveScriptFileButton = QtWidgets.QPushButton(self.scriptTab)
        self.saveScriptFileButton.setGeometry(QtCore.QRect(400, 430, 61, 31))
        self.saveScriptFileButton.setObjectName("saveScriptFileButton")
        self.centerTabWidget.addTab(self.scriptTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_variables = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_variables.setGeometry(QtCore.QRect(20, 60, 221, 371))
        self.tableWidget_variables.setRowCount(2)
        self.tableWidget_variables.setColumnCount(2)
        self.tableWidget_variables.setObjectName("tableWidget_variables")
        self.centerTabWidget.addTab(self.tab, "")
        self.grid_opengl.addWidget(self.centerTabWidget, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.grid_opengl, 4, 3, 10, 8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar_buffer = QtWidgets.QProgressBar(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_buffer.sizePolicy().hasHeightForWidth())
        self.progressBar_buffer.setSizePolicy(sizePolicy)
        self.progressBar_buffer.setMaximumSize(QtCore.QSize(300, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.progressBar_buffer.setFont(font)
        self.progressBar_buffer.setProperty("value", 0)
        self.progressBar_buffer.setObjectName("progressBar_buffer")
        self.verticalLayout_2.addWidget(self.progressBar_buffer)
        self.progressBar_job = QtWidgets.QProgressBar(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_job.sizePolicy().hasHeightForWidth())
        self.progressBar_job.setSizePolicy(sizePolicy)
        self.progressBar_job.setMaximumSize(QtCore.QSize(300, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.progressBar_job.setFont(font)
        self.progressBar_job.setProperty("value", 0)
        self.progressBar_job.setObjectName("progressBar_job")
        self.verticalLayout_2.addWidget(self.progressBar_job)
        self.gridLayout.addLayout(self.verticalLayout_2, 16, 12, 1, 3)
        self.doubleSpinBox_jogstep = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_jogstep.setDecimals(1)
        self.doubleSpinBox_jogstep.setMinimum(0.1)
        self.doubleSpinBox_jogstep.setMaximum(10.0)
        self.doubleSpinBox_jogstep.setSingleStep(0.1)
        self.doubleSpinBox_jogstep.setProperty("value", 1.0)
        self.doubleSpinBox_jogstep.setObjectName("doubleSpinBox_jogstep")
        self.gridLayout.addWidget(self.doubleSpinBox_jogstep, 10, 0, 1, 1)
        self.listWidget_logoutput = QtWidgets.QListWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_logoutput.sizePolicy().hasHeightForWidth())
        self.listWidget_logoutput.setSizePolicy(sizePolicy)
        self.listWidget_logoutput.setMinimumSize(QtCore.QSize(300, 0))
        self.listWidget_logoutput.setMaximumSize(QtCore.QSize(16777, 16777215))
        self.listWidget_logoutput.setObjectName("listWidget_logoutput")
        self.gridLayout.addWidget(self.listWidget_logoutput, 8, 12, 5, 3)
        self.scrollArea_loginput = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_loginput.sizePolicy().hasHeightForWidth())
        self.scrollArea_loginput.setSizePolicy(sizePolicy)
        self.scrollArea_loginput.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea_loginput.setMaximumSize(QtCore.QSize(16777, 16777215))
        self.scrollArea_loginput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_loginput.setWidgetResizable(True)
        self.scrollArea_loginput.setObjectName("scrollArea_loginput")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 285, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_loginput.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea_loginput, 4, 12, 4, 3)
        self.pushButton_filestream = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_filestream.sizePolicy().hasHeightForWidth())
        self.pushButton_filestream.setSizePolicy(sizePolicy)
        self.pushButton_filestream.setObjectName("pushButton_filestream")
        self.gridLayout.addWidget(self.pushButton_filestream, 0, 13, 1, 1)
        self.checkBox_incremental = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_incremental.setObjectName("checkBox_incremental")
        self.gridLayout.addWidget(self.checkBox_incremental, 0, 14, 1, 1)
        self.pushButton_fileload = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_fileload.setObjectName("pushButton_fileload")
        self.gridLayout.addWidget(self.pushButton_fileload, 0, 12, 1, 1)
        self.pushButton_check = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_check.setObjectName("pushButton_check")
        self.gridLayout.addWidget(self.pushButton_check, 0, 10, 1, 1)
        self.line_edit_devicePath = QtWidgets.QLineEdit(self.centralWidget)
        self.line_edit_devicePath.setObjectName("line_edit_devicePath")
        self.gridLayout.addWidget(self.line_edit_devicePath, 0, 7, 1, 3)
        self.label_grbl = QtWidgets.QLabel(self.centralWidget)
        self.label_grbl.setGeometry(QtCore.QRect(279, 493, 334, 31))
        self.label_grbl.setText("")
        self.label_grbl.setObjectName("label_grbl")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.centerTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_w2mcoord.setText(_translate("MainWindow", "W -> M"))
        self.pushButton_xplus.setText(_translate("MainWindow", "X→"))
        self.pushButton_xminus.setText(_translate("MainWindow", "←X"))
        self.pushButton_killalarm.setText(_translate("MainWindow", "Kill Alarm"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.pushButton_hold.setText(_translate("MainWindow", "Hold !"))
        self.pushButton_g0wzero.setText(_translate("MainWindow", "Goto 0"))
        self.pushButton_zeroxy.setText(_translate("MainWindow", "Zero XY"))
        self.pushButton_g0wzerosafe.setText(_translate("MainWindow", "+Z Goto 0"))
        self.pushButton_zeroz.setText(_translate("MainWindow", "Zero Z"))
        self.pushButton_zplus.setText(_translate("MainWindow", "Z↑"))
        self.pushButton_homing.setText(_translate("MainWindow", "Homing"))
        self.pushButton_resume.setText(_translate("MainWindow", "Resume ~"))
        self.label_distancemode.setText(_translate("MainWindow", "dist mode"))
        self.pushButton_yplus.setText(_translate("MainWindow", "Y↗"))
        self.checkBox_feedoverride.setText(_translate("MainWindow", "Feed override"))
        self.pushButton_abort.setText(_translate("MainWindow", "Abrt / Rset"))
        self.label_arcdistancemode.setText(_translate("MainWindow", "arc dist mode"))
        self.pushButton_zeroxyz.setText(_translate("MainWindow", "Zero XYZ"))
        self.label_state.setText(_translate("MainWindow", "disconnected"))
        self.pushButton_zminus.setText(_translate("MainWindow", "Z↓"))
        self.pushButton_yminus.setText(_translate("MainWindow", "Y↙"))
        self.centerTabWidget.setTabText(self.centerTabWidget.indexOf(self.glTab), _translate("MainWindow", "Simulation"))
        self.pocketButton.setText(_translate("MainWindow", "Pocket"))
        self.pocketButtonLabel.setText(_translate("MainWindow", "sx,sy,ex,ey,depth"))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "Settings"))
        self.bitDiameterLabel.setText(_translate("MainWindow", "Bit Diameter"))
        self.argumentsGroupBox.setTitle(_translate("MainWindow", "Arguments"))
        self.rLabel.setText(_translate("MainWindow", "radius"))
        self.syLabel.setText(_translate("MainWindow", "sy/k"))
        self.eyLabel.setText(_translate("MainWindow", "ey"))
        self.dLabel.setText(_translate("MainWindow", "depth"))
        self.exLabel.setText(_translate("MainWindow", "ex"))
        self.sxLabel.setText(_translate("MainWindow", "sx/h"))
        self.centerTabWidget.setTabText(self.centerTabWidget.indexOf(self.conversationTab), _translate("MainWindow", "Conversation"))
        self.linesToExecuteLabel.setText(_translate("MainWindow", "Lines"))
        self.filenameLabel.setText(_translate("MainWindow", "Filename"))
        self.loadScriptButton.setText(_translate("MainWindow", "Load"))
        self.windowScopeCheckbox.setText(_translate("MainWindow", "Window"))
        self.compilerScopeCheckbox.setText(_translate("MainWindow", "Compiler"))
        self.executeScriptButton.setText(_translate("MainWindow", "Execute"))
        self.linesToExecute.setText(_translate("MainWindow", "0"))
        self.saveScriptFileButton.setText(_translate("MainWindow", "Save"))
        self.centerTabWidget.setTabText(self.centerTabWidget.indexOf(self.scriptTab), _translate("MainWindow", "Script"))
        self.centerTabWidget.setTabText(self.centerTabWidget.indexOf(self.tab), _translate("MainWindow", "Preprocessor"))
        self.pushButton_filestream.setText(_translate("MainWindow", "Stream File"))
        self.checkBox_incremental.setText(_translate("MainWindow", "Incremental"))
        self.pushButton_fileload.setText(_translate("MainWindow", "Set File"))
        self.pushButton_check.setText(_translate("MainWindow", "Check"))

