# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib/qt/cnctoolbox/mainwindow.ui'
#
# Created: Sun Apr  5 12:20:54 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 603)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label_heading = QtWidgets.QLabel(self.centralWidget)
        self.label_heading.setGeometry(QtCore.QRect(350, 0, 211, 41))
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Pagella")
        font.setPointSize(36)
        font.setItalic(True)
        self.label_heading.setFont(font)
        self.label_heading.setObjectName("label_heading")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 160, 651, 371))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_opengl = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_opengl.setContentsMargins(0, 0, 0, 0)
        self.grid_opengl.setObjectName("grid_opengl")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 160, 191, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_xyz = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_xyz.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_xyz.setObjectName("verticalLayout_xyz")
        self.lcdNumber_x = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.lcdNumber_x.setDigitCount(6)
        self.lcdNumber_x.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_x.setObjectName("lcdNumber_x")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_x)
        self.lcdNumber_y = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.lcdNumber_y.setDigitCount(6)
        self.lcdNumber_y.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_y.setObjectName("lcdNumber_y")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_y)
        self.lcdNumber_z = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.lcdNumber_z.setSmallDecimalPoint(False)
        self.lcdNumber_z.setDigitCount(6)
        self.lcdNumber_z.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_z.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_z.setObjectName("lcdNumber_z")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_z)
        self.textedit_commandline = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.textedit_commandline.setGeometry(QtCore.QRect(240, 120, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textedit_commandline.setFont(font)
        self.textedit_commandline.setObjectName("textedit_commandline")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(30, 60, 95, 31))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(140, 60, 95, 31))
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.pushButton_homing = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_homing.setGeometry(QtCore.QRect(250, 60, 95, 31))
        self.pushButton_homing.setObjectName("pushButton_homing")
        self.pushButton_killalarm = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_killalarm.setGeometry(QtCore.QRect(360, 60, 95, 31))
        self.pushButton_killalarm.setObjectName("pushButton_killalarm")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(470, 60, 95, 31))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_pause = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_pause.setGeometry(QtCore.QRect(80, 320, 95, 31))
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.pushButton_resume = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_resume.setGeometry(QtCore.QRect(80, 360, 95, 31))
        self.pushButton_resume.setObjectName("pushButton_resume")
        self.pushButton_abort = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_abort.setGeometry(QtCore.QRect(80, 400, 95, 31))
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.label_grbl = QtWidgets.QLabel(self.centralWidget)
        self.label_grbl.setGeometry(QtCore.QRect(240, 540, 361, 21))
        self.label_grbl.setText("")
        self.label_grbl.setObjectName("label_grbl")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setGeometry(QtCore.QRect(770, 540, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_fileload = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_fileload.setGeometry(QtCore.QRect(800, 60, 95, 31))
        self.pushButton_fileload.setObjectName("pushButton_fileload")
        self.label_file = QtWidgets.QLabel(self.centralWidget)
        self.label_file.setGeometry(QtCore.QRect(390, 90, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_file.setFont(font)
        self.label_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_file.setObjectName("label_file")
        self.pushButton_filestream = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_filestream.setGeometry(QtCore.QRect(700, 60, 95, 31))
        self.pushButton_filestream.setObjectName("pushButton_filestream")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_heading.setText(_translate("MainWindow", "cnctoolbox"))
        self.textedit_commandline.setPlainText(_translate("MainWindow", "G0 X0 Y0 Z0"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pushButton_homing.setText(_translate("MainWindow", "Homing"))
        self.pushButton_killalarm.setText(_translate("MainWindow", "Kill Alarm"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_resume.setText(_translate("MainWindow", "Resume"))
        self.pushButton_abort.setText(_translate("MainWindow", "Abort"))
        self.pushButton_fileload.setText(_translate("MainWindow", "Load File"))
        self.label_file.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_filestream.setText(_translate("MainWindow", "Stream File"))

